services:
  personal-site:
    image: ghcr.io/eiplsoma/personal_site:${IMAGE_TAG:?IMAGE_TAG must be set}
    container_name: personal-site
    restart: unless-stopped
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: web
